feat: implementation of new features
nutsfinance/tapio-eth pull request #58
Opened 2024-12-09 12:47 UTC by 0xSolDev

2024-12-29 09:14 UTC, zakrad approved these changes

2025-01-05 14:00 UTC, zakrad requested changes

2025-01-05 14:00 UTC, zakrad commented on src/LPToken.sol
> +
missing natspec

2025-01-05 14:00 UTC, zakrad commented on src/SelfPeggingAssetFactory.sol
> +        selfPeggingAsset.setAdmin(governor, true);
is there reason we are not using admins as owner of contract in `selfPeggingAsset`?

2025-01-05 14:00 UTC, zakrad commented on src/SelfPeggingAssetFactory.sol
> +        lpToken.addPool(address(selfPeggingAsset));
does this mean we only add one pool per `lpToken` ? sicne the ownership is transferred its not possible to create another pool with same lpToken right?

2025-01-05 14:00 UTC, zakrad commented on src/SelfPeggingAssetFactory.sol
> +        executors[0] = governor;
seems redundant

2025-01-05 14:00 UTC, zakrad commented on src/misc/ERC4626ExchangeRate.sol
> +        return token.convertToAssets(1e18);
does it only works with erc4626 with 18 decimals?

2025-01-05 14:00 UTC, zakrad commented on src/misc/OracleExchangeRate.sol
> +    string public func;
it would be cleaner to get function selector instead of string and even compacting it with oracle address in one bytes32 immutable slot for optimization since its not upgradeable

2025-01-05 16:12 UTC, azat-hafizov approved these changes

2025-01-05 16:26 UTC, 0xSolDev commented on src/SelfPeggingAssetFactory.sol
> +        selfPeggingAsset.setAdmin(governor, true);
An admin role is different. Admins can pause/unpause a pool and during the time it's paused they can mint/redeem/swap.

2025-01-05 16:27 UTC, 0xSolDev commented on src/SelfPeggingAssetFactory.sol
> +        lpToken.addPool(address(selfPeggingAsset));
Yes the requirement is to have only one pool in a lptoken

2025-01-05 16:48 UTC, 0xSolDev commented on src/misc/OracleExchangeRate.sol
> +    string public func;
I made it this way so that it's easier to specify the function name in the UI or in the explorer.

2025-01-05 16:49 UTC, 0xSolDev commented on src/misc/ERC4626ExchangeRate.sol
> +        return token.convertToAssets(1e18);
Changed it to get the decimals dynamically

2025-01-05 22:25 UTC, zakrad requested changes

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +        amountPositive[_j] = true;
is there a point for emiting this array, its always fixed for input/output

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +            Ann = Ann * _balances.length;
this Ann recalculates inside the loop for no reason

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +        uint256 y = _getY(_balances, _i, D - redeemAmount);
not sure if it the correct way to calculate y when redeeming creates imbalance, in main impl the [new D](https://github.com/curvefi/stableswap-ng/blob/af7685d3f1389ab6a244f9c35c91603b10dcfa48/contracts/main/CurveStableSwapNG.vy#L1234) calculated based on proportion of totalSupply and D0 is different from totalSupply

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +            // balance = balance + amount * precision
balance = balance - amount * precision

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +            // balance = balance + amount * precision
balance = balance - amount * precision

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAsset.sol
> +        totalSupply = oldD - redeemAmount;
same thing [here](https://github.com/curvefi/stableswap-ng/blob/af7685d3f1389ab6a244f9c35c91603b10dcfa48/contracts/main/CurveStableSwapNG.vy#L778) as redeemSingle, it also +1 for rounding error

2025-01-05 22:25 UTC, zakrad commented on src/SelfPeggingAssetFactory.sol
> +import "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";
this is not used

2025-01-06 13:17 UTC, zakrad approved these changes

2025-01-10 05:28 UTC, closed without merging